### PR TITLE
Fix postgres ssl modes to work without explicit root certificate

### PR DESCRIPTION
**Pull request by maab**
Fix postgres ssl modes `require`, `verify-ca` and `verify-full` to work without explicit root certificate.

This PR simplifies the checks and the building rules of the postgres connection and moves the responsibility for error checking to the database library.

### CODE REVIEW

**Comment by maab** [comment]
Hi @NickUfer, do you see any chance for a review in the next days?

**Comment by NickUfer** [comment]
> Hi @NickUfer, do you see any chance for a review in the next days?

Yes, sorry for the delay. I got sick during the trip and there was more stuff to do during the trip than I thought. I try to look into this later today

**Comment by NickUfer** [comment]
Looks good, will merge and make a small adjustments which don't undermine your changes, so we can go forward faster

**Comment by NickUfer** [comment]
My additional changes https://github.com/NickUfer/mosquitto-go-auth/commit/6df8b7a6b1623e85ff9235ef7c9a4dc5bbed5cb7

**Pull request merged**
